/* Terra Nova — vague 18 (D10, F91, F92) : base de connaissances du moteur d'orientation (contenu, aucune IA générative).
   - CONCEPTS : familles de mots et expressions familières, en français, anglais, espagnol et arabe, qui veulent dire la même chose
     (« poubelle », « benne », « bin », « basura », « قمامة » → déchets). Comparés après normalisation et racinisation.
   - BESOINS : les démarches, signalements et questions courantes (service compétent, type d'action, documents, expressions des habitants).
   - REPONSES : questions fréquentes avec leur réponse courte, en quatre langues.
   Les agents enrichissent les expressions depuis « Questions sans réponse » (collection orientationSynonymes, src/modules/orientation.js). */
'use strict';

const L = (fr, en, es, ar) => ({ fr, en, es: es || en, ar: ar || en });

/* ---------- Familles de mots (concepts) ---------- */
const CONCEPTS = {
  eclairage: ['lampadaire', 'lampadaires', 'reverbere', 'eclairage', 'eclairages', 'lumiere', 'lumieres', 'lampe', 'ampoule', 'streetlight', 'streetlamp', 'lamppost', 'light', 'lights', 'lamp', 'farola', 'farolas', 'alumbrado', 'luz', 'اناره', 'عمود الانارة', 'مصباح', 'ضوء'],
  panne: ['casse', 'cassee', 'casses', 'panne', 'eteint', 'eteinte', 'eteints', 'marche plus', 'fonctionne plus', 'abime', 'abimee', 'defectueux', 'hs', 'clignote', 'broken', 'damaged', 'not working', 'flickering', 'roto', 'rota', 'averiado', 'averiada', 'apagado', 'apagada', 'معطل', 'مكسور', 'مطفا'],
  dechet: ['poubelle', 'poubelles', 'ordure', 'ordures', 'dechet', 'dechets', 'benne', 'conteneur', 'container', 'bac', 'detritus', 'immondices', 'sac poubelle', 'collecte', 'ramassage', 'eboueur', 'trash', 'rubbish', 'garbage', 'bin', 'bins', 'waste', 'litter', 'basura', 'residuos', 'contenedor', 'cubo', 'recogida', 'نفايات', 'قمامه', 'زباله', 'حاويه'],
  deborde: ['deborde', 'debordent', 'deborder', 'plein', 'pleine', 'pleines', 'remplie', 'pas ramasse', 'pas ramassee', 'overflowing', 'full', 'not collected', 'lleno', 'llena', 'desborda', 'ممتلئ', 'ممتلئه'],
  encombrant: ['encombrant', 'encombrants', 'meuble', 'meubles', 'matelas', 'frigo', 'refrigerateur', 'electromenager', 'canape', 'bulky', 'furniture', 'mattress', 'sofa', 'fridge', 'voluminoso', 'muebles', 'colchon', 'nevera', 'اثاث', 'ثلاجه'],
  eau: ['eau', 'eaux', 'flotte', 'robinet', 'robinets', 'tuyau', 'canalisation', 'plomberie', 'water', 'tap', 'pipe', 'agua', 'grifo', 'tuberia', 'ماء', 'مياه', 'حنفيه'],
  fuite: ['fuite', 'fuit', 'fuites', 'inondation', 'inonde', 'goutte', 'perce', 'leak', 'leaking', 'leaks', 'burst', 'fuga', 'gotea', 'goteo', 'تسرب', 'تسريب'],
  coupure: ['coupure', 'coupe', 'coupee', 'plus d eau', 'pas d eau', 'sans eau', 'coule plus', 'coule pas', 'plus de courant', 'outage', 'cut off', 'no water', 'without water', 'corte', 'cortado', 'sin agua', 'no hay agua', 'انقطاع', 'مقطوع'],
  electricite: ['electricite', 'electrique', 'courant', 'energie', 'prise', 'compteur', 'disjoncteur', 'electricity', 'power', 'energy', 'electricidad', 'كهرباء'],
  facture: ['facture', 'factures', 'payer', 'paiement', 'montant', 'consommation', 'trop cher', 'bill', 'bills', 'invoice', 'factura', 'pagar', 'recibo', 'فاتوره', 'دفع'],
  mariage: ['mariage', 'marier', 'marie', 'epouser', 'noces', 'pacs', 'pacser', 'fiance', 'wedding', 'marriage', 'marry', 'married', 'boda', 'casar', 'casarse', 'casarme', 'matrimonio', 'زواج', 'عرس', 'زفاف', 'الزواج'],
  naissance: ['naissance', 'bebe', 'nouveau ne', 'accouche', 'birth', 'born', 'baby', 'newborn', 'nacimiento', 'nacido', 'ولاده', 'ميلاد', 'مولود'],
  acte: ['acte', 'actes', 'certificat', 'extrait', 'copie', 'attestation', 'certificate', 'copy', 'acta', 'certificado', 'partida', 'شهاده', 'وثيقه', 'عقد'],
  papiers: ['papier', 'papiers', 'identite', 'carte d identite', 'cni', 'passeport', 'passport', 'id', 'identity', 'documento', 'documentos', 'pasaporte', 'dni', 'هويه', 'جواز', 'بطاقه', 'اوراق'],
  adresse: ['demenager', 'demenagement', 'demenage', 'nouvelle adresse', 'adresse', 'emmenage', 'move', 'moving', 'moved', 'address', 'mudanza', 'mudarme', 'mudado', 'mudar', 'direccion', 'domicilio', 'عنوان', 'انتقلت', 'انتقال'],
  logement: ['logement', 'logements', 'appartement', 'appart', 'module', 'habitation', 'loyer', 'location', 'bail', 'housing', 'flat', 'apartment', 'home', 'house', 'rent', 'vivienda', 'piso', 'alquiler', 'سكن', 'شقه', 'منزل', 'بيت', 'ايجار'],
  sansabri: ['sdf', 'sans abri', 'a la rue', 'dormir dehors', 'dehors', 'hebergement', 'expulse', 'expulsion', 'homeless', 'shelter', 'evicted', 'nowhere to sleep', 'sin hogar', 'desahucio', 'albergue', 'donde dormir', 'مشرد', 'ماوي', 'مأوى'],
  reparation: ['reparation', 'reparer', 'moisissure', 'humidite', 'chauffage', 'climatisation', 'porte cassee', 'fenetre cassee', 'repair', 'repairs', 'fix', 'mold', 'mould', 'heating', 'reparar', 'arreglar', 'humedad', 'calefaccion', 'اصلاح', 'تصليح', 'رطوبه'],
  urbanisme: ['permis', 'permis de construire', 'extension', 'agrandir', 'agrandissement', 'construire', 'veranda', 'terrasse', 'autorisation de travaux', 'travaux', 'building permit', 'extend', 'planning', 'licencia de obras', 'ampliar', 'construir', 'obras', 'رخصه بناء', 'توسيع', 'بناء'],
  ecole: ['ecole', 'scolaire', 'classe', 'college', 'eleve', 'rentree', 'maternelle', 'school', 'enrol', 'enroll', 'pupil', 'escuela', 'colegio', 'matricula', 'matricular', 'مدرسه', 'تلميذ', 'المدرسة'],
  enfant: ['enfant', 'enfants', 'fils', 'fille', 'gamin', 'gosse', 'petit', 'petite', 'child', 'children', 'kid', 'kids', 'son', 'daughter', 'nino', 'nina', 'hijo', 'hija', 'hijos', 'طفل', 'اطفال', 'ابن', 'ابني', 'ابنه'],
  creche: ['creche', 'garderie', 'nounou', 'petite enfance', 'faire garder', 'nursery', 'daycare', 'childcare', 'guarderia', 'حضانه'],
  cantine: ['cantine', 'repas', 'restauration scolaire', 'canteen', 'lunch', 'school meals', 'comedor', 'مطعم'],
  emploi: ['emploi', 'travail', 'travailler', 'boulot', 'job', 'taf', 'chomage', 'chomeur', 'embauche', 'cv', 'recrutement', 'work', 'unemployed', 'empleo', 'trabajo', 'trabajar', 'paro', 'عمل', 'وظيفه', 'شغل', 'بطاله'],
  formation: ['formation', 'formations', 'apprendre', 'cours', 'diplome', 'stage', 'apprentissage', 'training', 'course', 'learn', 'formacion', 'curso', 'تكوين', 'تدريب', 'دوره'],
  aide: ['aide', 'aides', 'allocation', 'soutien', 'subvention', 'precarite', 'difficulte', 'difficultes', 'galere', 'support', 'welfare', 'benefit', 'benefits', 'ayuda', 'ayudas', 'subsidio', 'مساعده', 'دعم', 'اعانه'],
  argent: ['argent', 'sous', 'fric', 'thune', 'ressources', 'revenus', 'budget', 'dettes', 'fin de mois', 'money', 'cash', 'broke', 'afford', 'dinero', 'plata', 'deuda', 'مال', 'فلوس', 'نقود', 'ديون'],
  alimentation: ['manger', 'faim', 'nourriture', 'colis', 'epicerie', 'alimentaire', 'food', 'hungry', 'eat', 'comida', 'hambre', 'comer', 'اكل', 'طعام', 'جوع'],
  social: ['social', 'sociale', 'assistante sociale', 'assistant social', 'travailleur social', 'accompagnement', 'social worker', 'trabajador social', 'trabajadora social', 'اجتماعي', 'اجتماعيه'],
  sante: ['sante', 'malade', 'maladie', 'medecin', 'docteur', 'soigner', 'soins', 'consultation', 'dispensaire', 'infirmier', 'infirmiere', 'fievre', 'douleur', 'health', 'sick', 'ill', 'doctor', 'clinic', 'nurse', 'salud', 'enfermo', 'enferma', 'medico', 'clinica', 'صحه', 'مريض', 'طبيب', 'مستوصف', 'علاج'],
  vaccin: ['vaccin', 'vaccins', 'vaccination', 'vacciner', 'piqure', 'rappel', 'vaccine', 'shot', 'jab', 'vacuna', 'vacunar', 'تطعيم', 'لقاح'],
  pharmacie: ['pharmacie', 'medicament', 'medicaments', 'ordonnance', 'pharmacy', 'chemist', 'medicine', 'farmacia', 'medicamento', 'صيدليه', 'دواء'],
  urgence: ['urgence', 'urgent', 'samu', 'ambulance', 'pompiers', 'secours', 'emergency', 'urgencia', 'ambulancia', 'طوارئ', 'اسعاف'],
  transport: ['navette', 'navettes', 'bus', 'tram', 'transport', 'transports', 'ligne', 'arret', 'trajet', 'shuttle', 'line', 'stop', 'transporte', 'lanzadera', 'autobus', 'linea', 'parada', 'حافله', 'نقل', 'خط'],
  horaire: ['horaire', 'horaires', 'heure', 'quelle heure', 'prochain', 'prochaine', 'passe', 'ouvert', 'ouverte', 'ouverture', 'ferme', 'schedule', 'timetable', 'next', 'opening hours', 'open', 'horario', 'horarios', 'abierto', 'proximo', 'مواعيد', 'مفتوح', 'ساعه'],
  abonnement: ['abonnement', 'pass', 'carte de transport', 'carte de bus', 'ticket', 'billet', 'mensuel', 'subscription', 'monthly', 'abono', 'billete', 'اشتراك', 'تذكره'],
  reduction: ['reduit', 'reduction', 'gratuit', 'moins cher', 'etudiant', 'senior', 'demi tarif', 'reduced', 'discount', 'free', 'concession', 'descuento', 'gratis', 'reducido', 'تخفيض', 'مجاني'],
  perdu: ['perdu', 'perdue', 'oublie', 'oubliee', 'egare', 'objet trouve', 'lost', 'forgot', 'forgotten', 'left', 'perdido', 'perdida', 'olvide', 'olvidado', 'مفقود', 'نسيت', 'ضاع'],
  route: ['trou', 'trous', 'nid de poule', 'chaussee', 'route', 'rue', 'trottoir', 'bitume', 'goudron', 'pothole', 'road', 'street', 'pavement', 'sidewalk', 'bache', 'calle', 'acera', 'carretera', 'حفره', 'طريق', 'رصيف', 'شارع'],
  bruit: ['bruit', 'bruits', 'bruyant', 'bruyants', 'tapage', 'musique', 'voisin', 'voisins', 'voisinage', 'nuisance', 'nuisances', 'noise', 'noisy', 'loud', 'neighbour', 'neighbours', 'neighbor', 'neighbors', 'ruido', 'vecino', 'vecinos', 'ruidoso', 'ruidosos', 'ضجيج', 'ازعاج', 'جيران'],
  danger: ['danger', 'dangereux', 'risque', 'cable', 'fil electrique', 'tombe', 'effondre', 'gaz', 'odeur de gaz', 'dangerous', 'hazard', 'gas', 'fallen', 'peligro', 'peligroso', 'خطر', 'غاز'],
  culture: ['mediatheque', 'bibliotheque', 'livre', 'livres', 'emprunter', 'lecture', 'observatoire', 'spectacle', 'concert', 'exposition', 'library', 'book', 'books', 'borrow', 'biblioteca', 'libro', 'libros', 'مكتبه', 'كتاب'],
  sport: ['sport', 'sports', 'gym', 'salle de sport', 'piscine', 'foot', 'football', 'basket', 'stade', 'gymnase', 'swimming', 'pool', 'deporte', 'gimnasio', 'piscina', 'رياضه', 'مسبح', 'ملعب'],
  suivi: ['suivre', 'suivi', 'ou en est', 'avancement', 'statut', 'dossier', 'nt', 'pas de reponse', 'sans reponse', 'nouvelles', 'track', 'tracking', 'status', 'progress', 'seguimiento', 'estado', 'seguir', 'متابعه', 'حاله'],
  rdv: ['rendez vous', 'rdv', 'creneau', 'rencontrer', 'appointment', 'meeting', 'booking', 'slot', 'cita', 'reservar', 'موعد', 'حجز'],
  compte: ['compte', 'mot de passe', 'connexion', 'connecter', 'identifiant', 'login', 'password', 'account', 'sign in', 'log in', 'cuenta', 'contrasena', 'iniciar sesion', 'حساب', 'كلمه السر', 'دخول'],
  donnees: ['donnees', 'donnees personnelles', 'vie privee', 'rgpd', 'informations personnelles', 'data', 'privacy', 'personal data', 'datos', 'privacidad', 'بيانات', 'خصوصيه'],
  arrivee: ['arrive', 'arrivee', 'arriver', 'nouvel arrivant', 'nouveau venu', 'installer', 'installation', 'arrived', 'new here', 'newcomer', 'settle', 'recien llegado', 'acabo de llegar', 'llegue', 'وصلت', 'جديد'],
  mairie: ['mairie', 'hotel de ville', 'accueil', 'guichet', 'town hall', 'city hall', 'ayuntamiento', 'بلديه', 'البلدية'],
  plainte: ['reclamation', 'plainte', 'contester', 'plaindre', 'mecontent', 'complain', 'complaint', 'queja', 'reclamacion', 'شكوي', 'شكوى'],
  deces: ['deces', 'decede', 'decedee', 'mort', 'morte', 'mourir', 'enterrement', 'obseques', 'funerailles', 'death', 'died', 'dead', 'funeral', 'defuncion', 'fallecimiento', 'fallecido', 'muerto', 'entierro', 'وفاه', 'دفن', 'جنازه', 'توفي'],
  chaleur: ['chaleur', 'canicule', 'chaud', 'etouffant', 'lieu frais', 'heatwave', 'heat', 'hot', 'calor', 'ola de calor', 'حر', 'حراره'],
  crue: ['crue', 'montee des eaux', 'niveau de l eau', 'flood', 'flooding', 'inundacion', 'crecida', 'فيضان']
};

/* ---------- Services : téléphone, lieu sur la carte, familles de mots ---------- */
const SERVICES = {
  'etat-civil': { tel: '01 55 00 10 00', lieu: 'hotel-ville', concepts: ['acte', 'papiers', 'mariage', 'naissance', 'adresse', 'deces', 'mairie'] },
  sante: { tel: '01 55 00 15 15', lieu: 'dispensaire-central', concepts: ['sante', 'vaccin', 'pharmacie', 'urgence'] },
  logement: { tel: '01 55 00 13 20', lieu: 'pole-habitat', concepts: ['logement', 'reparation', 'sansabri'] },
  transports: { tel: '01 55 00 16 10', lieu: 'gare-orbitale', concepts: ['transport', 'abonnement', 'reduction', 'perdu', 'horaire'] },
  'eau-energie': { tel: '01 55 00 10 00', lieu: '', concepts: ['eau', 'electricite', 'facture', 'coupure', 'fuite'] },
  voirie: { tel: '01 55 00 13 10', lieu: 'centre-technique', concepts: ['eclairage', 'route', 'panne', 'danger'] },
  education: { tel: '01 55 00 14 20', lieu: 'maison-enfance', concepts: ['ecole', 'enfant', 'creche', 'cantine'] },
  dechets: { tel: '01 55 00 15 10', lieu: 'centre-tri', concepts: ['dechet', 'encombrant', 'deborde', 'bruit'] },
  emploi: { tel: '01 55 00 13 30', lieu: 'maison-emploi', concepts: ['emploi', 'formation'] },
  social: { tel: '01 55 00 14 10', lieu: 'centre-social', concepts: ['aide', 'argent', 'alimentation', 'social', 'sansabri'] },
  culture: { tel: '01 55 00 15 20', lieu: 'mediatheque', concepts: ['culture', 'sport'] },
  urbanisme: { tel: '01 55 00 10 00', lieu: 'hotel-ville', concepts: ['urbanisme'] }
};

/* ---------- Étapes types, selon le genre d'action (le besoin peut les remplacer) ---------- */
const ETAPES = {
  demarche: L(['Préparez les documents listés ci-dessous.', 'Faites la demande en ligne : 2 minutes, un numéro de suivi NT-xxxx vous est donné.', 'Le service vous répond sous 5 jours ouvrés, étape par étape dans « Suivre mes demandes ».'],
    ['Get the documents listed below ready.', 'Make the request online: 2 minutes, you get an NT-xxxx tracking number.', 'The service answers within 5 working days; follow each step in “Track my requests”.'],
    ['Prepare los documentos indicados abajo.', 'Haga la solicitud en línea: 2 minutos, recibe un número de seguimiento NT-xxxx.', 'El servicio responde en 5 días laborables; siga cada etapa en «Seguir mis solicitudes».'],
    ['جهّز الوثائق المذكورة أدناه.', 'قدّم الطلب عبر الإنترنت: دقيقتان، وتحصل على رقم متابعة NT-xxxx.', 'تردّ الخدمة خلال 5 أيام عمل؛ تابع كل مرحلة في «متابعة طلباتي».']),
  signalement: L(['Dites ce que vous voyez et où, le plus précisément possible.', 'Ajoutez une photo si vous pouvez : l’équipe intervient plus vite.', 'Réponse sous 48 heures (4 heures si c’est dangereux) ; suivez l’intervention avec votre numéro.'],
    ['Say what you see and where, as precisely as possible.', 'Add a photo if you can: the team acts faster.', 'Answer within 48 hours (4 hours if dangerous); follow the work with your number.'],
    ['Diga qué ve y dónde, con la mayor precisión posible.', 'Añada una foto si puede: el equipo actúa más rápido.', 'Respuesta en 48 horas (4 horas si es peligroso); siga la intervención con su número.'],
    ['قل ماذا ترى وأين بأكبر دقة ممكنة.', 'أضف صورة إن أمكن: يتدخل الفريق أسرع.', 'الرد خلال 48 ساعة (4 ساعات إذا كان خطيراً)؛ تابع التدخل برقمك.']),
  contact: L(['Écrivez votre question au service en quelques lignes.', 'Vous recevez un numéro de suivi NT-xxxx.', 'Réponse sous 3 jours ouvrés, par message dans votre espace ou par e-mail.'],
    ['Write your question to the service in a few lines.', 'You get an NT-xxxx tracking number.', 'Answer within 3 working days, in your space or by e-mail.'],
    ['Escriba su pregunta al servicio en pocas líneas.', 'Recibe un número de seguimiento NT-xxxx.', 'Respuesta en 3 días laborables, en su espacio o por correo.'],
    ['اكتب سؤالك إلى الخدمة في بضعة أسطر.', 'تحصل على رقم متابعة NT-xxxx.', 'الرد خلال 3 أيام عمل، في فضائك أو بالبريد الإلكتروني.']),
  rdv: L(['Choisissez le service et un créneau libre.', 'Vous recevez la confirmation et un rappel la veille.', 'Venez avec les documents listés ci-dessous.'],
    ['Choose the service and a free slot.', 'You get a confirmation and a reminder the day before.', 'Come with the documents listed below.'],
    ['Elija el servicio y un horario libre.', 'Recibe la confirmación y un recordatorio la víspera.', 'Venga con los documentos indicados abajo.'],
    ['اختر الخدمة وموعداً متاحاً.', 'تصلك رسالة تأكيد وتذكير في اليوم السابق.', 'احضر مع الوثائق المذكورة أدناه.'])
};

/* ---------- Besoins (démarches, signalements, questions) ----------
   type : demarche | signalement | contact | rdv | info | urgence ; nature / categorie : valeurs de demande.html ; lien : page pour « info ».
   expressions : manières de dire des habitants (toutes langues), comparées telles quelles et mot à mot. */
const BESOINS = [
  { id: 'acte-naissance', service: 'etat-civil', type: 'demarche', nature: 'naissance', concepts: ['naissance', 'acte'], clair: 'demarche:naissance',
    titre: L('Acte de naissance', 'Birth certificate', 'Acta de nacimiento', 'شهادة ميلاد'),
    documents: L(['Pièce d’identité', 'Livret de famille si vous en avez un'], ['ID', 'Family record book if you have one'], ['Documento de identidad', 'Libro de familia si lo tiene'], ['وثيقة الهوية', 'دفتر العائلة إن وجد']),
    expressions: ['acte de naissance', 'extrait de naissance', 'papier de naissance', 'declarer une naissance', 'declarer mon bebe', 'mon bebe est ne', 'birth certificate', 'register a birth', 'acta de nacimiento', 'partida de nacimiento', 'شهادة ميلاد', 'تسجيل مولود'] },
  { id: 'acte-mariage', service: 'etat-civil', type: 'demarche', nature: 'mariage', concepts: ['mariage', 'acte'], clair: 'demarche:mariage',
    titre: L('Se marier ou obtenir un acte de mariage', 'Getting married or a marriage certificate', 'Casarse u obtener un acta de matrimonio', 'الزواج أو الحصول على عقد زواج'),
    documents: L(['Pièces d’identité des deux futurs époux', 'Justificatif de domicile de moins de 3 mois', 'Acte de naissance de moins de 3 mois'], ['ID of both future spouses', 'Proof of address less than 3 months old', 'Birth certificate less than 3 months old'], ['Documentos de identidad de ambos', 'Justificante de domicilio de menos de 3 meses', 'Acta de nacimiento de menos de 3 meses'], ['وثائق هوية الزوجين', 'إثبات السكن لا يتجاوز 3 أشهر', 'شهادة ميلاد لا تتجاوز 3 أشهر']),
    expressions: ['papier pour me marier', 'papiers pour se marier', 'je veux me marier', 'on veut se marier', 'se marier', 'dossier de mariage', 'acte de mariage', 'publication des bans', 'get married', 'marriage certificate', 'quiero casarme', 'acta de matrimonio', 'اريد الزواج', 'عقد زواج', 'وثيقة زواج'] },
  { id: 'changement-adresse', service: 'etat-civil', type: 'demarche', nature: 'adresse', concepts: ['adresse'], clair: 'demarche:adresse',
    titre: L('Déclarer un changement d’adresse', 'Report a change of address', 'Declarar un cambio de domicilio', 'التصريح بتغيير العنوان'),
    documents: L(['Justificatif du nouveau module (attribution ou bail)', 'Pièce d’identité'], ['Proof of your new module (allocation or lease)', 'ID'], ['Justificante del nuevo módulo', 'Documento de identidad'], ['إثبات الوحدة الجديدة', 'وثيقة الهوية']),
    expressions: ['j ai demenage', 'je demenage', 'nouvelle adresse', 'changer d adresse', 'changement d adresse', 'je change de module', 'i moved', 'change my address', 'new address', 'me he mudado', 'cambio de domicilio', 'cambiar mi direccion', 'تغيير العنوان', 'انتقلت الى سكن جديد'] },
  { id: 'papiers-identite', service: 'etat-civil', type: 'demarche', nature: 'identite', concepts: ['papiers'], clair: 'demarche:identite',
    titre: L('Carte d’identité ou passeport', 'ID card or passport', 'Documento de identidad o pasaporte', 'بطاقة الهوية أو جواز السفر'),
    documents: L(['Photo d’identité récente', 'Ancien titre (ou déclaration de perte ou de vol)', 'Justificatif d’adresse'], ['Recent ID photo', 'Previous document (or loss or theft report)', 'Proof of address'], ['Foto reciente', 'Documento anterior (o denuncia de pérdida o robo)', 'Justificante de domicilio'], ['صورة حديثة', 'الوثيقة القديمة (أو تصريح بالضياع أو السرقة)', 'إثبات العنوان']),
    expressions: ['carte d identite', 'refaire ma carte', 'renouveler ma carte', 'passeport', 'j ai perdu mes papiers', 'papiers perdus', 'on m a vole mes papiers', 'id card', 'lost my passport', 'renew my passport', 'renovar el dni', 'perdi mi pasaporte', 'بطاقة الهوية', 'جواز السفر', 'ضاعت اوراقي'] },
  { id: 'acte-deces', service: 'etat-civil', type: 'demarche', nature: 'autre', concepts: ['deces', 'acte'], clair: 'demarche:deces',
    titre: L('Déclarer un décès', 'Register a death', 'Declarar una defunción', 'التصريح بوفاة'),
    documents: L(['Certificat médical de décès', 'Pièce d’identité de la personne décédée', 'Votre pièce d’identité'], ['Medical death certificate', 'ID of the deceased', 'Your ID'], ['Certificado médico de defunción', 'Documento de identidad del fallecido', 'Su documento de identidad'], ['الشهادة الطبية للوفاة', 'هوية المتوفى', 'هويتك']),
    expressions: ['declarer un deces', 'acte de deces', 'quelqu un est decede', 'mon pere est decede', 'organiser des obseques', 'death certificate', 'someone died', 'certificado de defuncion', 'ha fallecido', 'شهادة وفاة', 'توفي والدي'] },
  { id: 'consultation-sante', service: 'sante', type: 'rdv', concepts: ['sante'],
    titre: L('Voir un médecin au dispensaire', 'See a doctor at the clinic', 'Ver a un médico en el dispensario', 'زيارة طبيب في المستوصف'),
    documents: L(['Pièce d’identité', 'Carte de santé'], ['ID', 'Health card'], ['Documento de identidad', 'Tarjeta sanitaria'], ['وثيقة الهوية', 'بطاقة الصحة']),
    expressions: ['voir un medecin', 'je suis malade', 'mon enfant est malade', 'consulter un docteur', 'rendez vous medecin', 'j ai de la fievre', 'see a doctor', 'i am sick', 'ver a un medico', 'estoy enfermo', 'اريد طبيب', 'انا مريض'] },
  { id: 'vaccination', service: 'sante', type: 'rdv', concepts: ['vaccin', 'sante'],
    titre: L('Se faire vacciner', 'Get vaccinated', 'Vacunarse', 'التطعيم'),
    documents: L(['Carnet de santé', 'Pièce d’identité'], ['Health record', 'ID'], ['Cartilla de salud', 'Documento de identidad'], ['دفتر الصحة', 'وثيقة الهوية']),
    expressions: ['faire un vaccin', 'vacciner mon enfant', 'rappel de vaccin', 'get vaccinated', 'vaccine appointment', 'vacunar a mi hijo', 'تطعيم ابني'] },
  { id: 'pharmacie-garde', service: 'sante', type: 'info', lien: 'carte.html?lieu=pharmacie-garde', concepts: ['pharmacie'],
    titre: L('Trouver la pharmacie de garde', 'Find the on-call pharmacy', 'Encontrar la farmacia de guardia', 'إيجاد الصيدلية المناوبة'),
    etapes: L(['Pharmacie de garde : quai des Arrivées, niveau 0.', 'Ouverte de 19h à 8h, et le dimanche 24 h/24.', 'Pour une urgence vitale, appelez le 15.'], ['On-call pharmacy: Arrivals quay, level 0.', 'Open 7pm to 8am, and 24/7 on Sundays.', 'For a life-threatening emergency, call 15.'], ['Farmacia de guardia: muelle de Llegadas, nivel 0.', 'Abierta de 19 h a 8 h y los domingos 24 h.', 'Para una urgencia vital, llame al 15.'], ['الصيدلية المناوبة: رصيف الوصول، الطابق 0.', 'مفتوحة من 19:00 إلى 8:00، ويوم الأحد على مدار الساعة.', 'في حالة طارئة اتصل بالرقم 15.']),
    expressions: ['pharmacie ouverte', 'pharmacie de garde', 'medicament la nuit', 'acheter des medicaments', 'pharmacy open', 'farmacia de guardia', 'صيدلية مناوبة'] },
  { id: 'demande-logement', service: 'logement', type: 'demarche', nature: 'autre', concepts: ['logement'], clair: 'demarche:logement-demande',
    titre: L('Demander un logement (module d’habitation)', 'Apply for housing (living module)', 'Solicitar una vivienda (módulo)', 'طلب سكن (وحدة سكنية)'),
    documents: L(['Justificatifs de revenus', 'Composition du foyer', 'Pièce d’identité'], ['Proof of income', 'Household composition', 'ID'], ['Justificantes de ingresos', 'Composición del hogar', 'Documento de identidad'], ['إثبات الدخل', 'تركيبة الأسرة', 'وثيقة الهوية']),
    expressions: ['chercher un logement', 'trouver un appartement', 'demande de logement', 'besoin d un logement', 'pas de logement', 'logement plus grand', 'looking for a flat', 'need housing', 'apply for a home', 'busco piso', 'necesito vivienda', 'ابحث عن سكن', 'اريد شقة'] },
  { id: 'aide-logement', service: 'logement', type: 'demarche', nature: 'logement', concepts: ['logement', 'aide', 'argent'], clair: 'demarche:logement',
    titre: L('Aide pour payer le loyer', 'Help paying the rent', 'Ayuda para pagar el alquiler', 'مساعدة لدفع الإيجار'),
    documents: L(['Avis de revenus', 'Attribution du module ou bail', 'Relevé d’identité bancaire'], ['Income statement', 'Module allocation or lease', 'Bank details'], ['Declaración de ingresos', 'Asignación o contrato', 'Datos bancarios'], ['كشف الدخل', 'قرار التخصيص أو عقد الإيجار', 'بيانات الحساب البنكي']),
    expressions: ['aide pour le loyer', 'payer mon loyer', 'aide au logement', 'allocation logement', 'loyer trop cher', 'help with rent', 'cannot pay rent', 'ayuda para el alquiler', 'no puedo pagar el alquiler', 'مساعدة في الايجار'] },
  { id: 'reparation-logement', service: 'logement', type: 'demarche', nature: 'autre', concepts: ['reparation', 'logement'],
    titre: L('Faire réparer quelque chose dans mon logement', 'Get something repaired in my home', 'Reparar algo en mi vivienda', 'إصلاح شيء في مسكني'),
    documents: L(['Description du problème', 'Photos si possible'], ['Description of the problem', 'Photos if possible'], ['Descripción del problema', 'Fotos si es posible'], ['وصف المشكلة', 'صور إن أمكن']),
    expressions: ['moisissure dans ma chambre', 'chauffage en panne', 'porte cassee', 'reparation dans mon logement', 'humidite chez moi', 'clim en panne', 'my flat needs repairs', 'heating not working', 'humedad en casa', 'calefaccion averiada', 'اصلاح في المنزل'] },
  { id: 'hebergement-urgence', service: 'social', type: 'contact', concepts: ['sansabri', 'logement'], prioritaire: true,
    titre: L('Être hébergé en urgence', 'Emergency accommodation', 'Alojamiento de urgencia', 'إيواء عاجل'),
    etapes: L(['Appelez le centre social au 01 55 00 14 10 (lundi au vendredi) ou présentez-vous place des Pionniers.', 'Le soir et le week-end : association Un toit pour tous.', 'Un travailleur social cherche une solution avec vous le jour même.'], ['Call the social centre on 01 55 00 14 10 (Mon–Fri) or go to Pioneers square.', 'Evenings and weekends: the association “A roof for all”.', 'A social worker looks for a solution with you the same day.'], ['Llame al centro social al 01 55 00 14 10 (lun–vie) o acuda a la plaza de los Pioneros.', 'Por la tarde y el fin de semana: asociación «Un techo para todos».', 'Un trabajador social busca una solución con usted el mismo día.'], ['اتصل بالمركز الاجتماعي على 01 55 00 14 10 (الاثنين–الجمعة) أو توجه إلى ساحة الرواد.', 'مساءً وفي نهاية الأسبوع: جمعية «سقف للجميع».', 'يبحث معك عامل اجتماعي عن حل في اليوم نفسه.']),
    expressions: ['dormir dehors', 'je suis a la rue', 'sans abri', 'expulse de mon logement', 'nulle part ou dormir', 'homeless', 'nowhere to sleep', 'evicted', 'sin hogar', 'no tengo donde dormir', 'ليس لدي مأوى'] },
  { id: 'horaires-navette', service: 'transports', type: 'info', lien: 'transports.html', concepts: ['transport', 'horaire'],
    titre: L('Horaires des navettes en direct', 'Live shuttle times', 'Horarios de las lanzaderas en directo', 'مواعيد الحافلات مباشرة'),
    etapes: L(['Ouvrez « Transports » : info trafic et 3 prochains départs.', 'Choisissez votre ligne (N1 à N4) et votre arrêt.', 'Les navettes passent toutes les 10 minutes, de 5h à 23h.'], ['Open “Transport”: traffic info and next 3 departures.', 'Choose your line (N1 to N4) and stop.', 'Shuttles run every 10 minutes, 5am to 11pm.'], ['Abra «Transportes»: tráfico y 3 próximas salidas.', 'Elija su línea (N1 a N4) y parada.', 'Pasan cada 10 minutos, de 5 h a 23 h.'], ['افتح «النقل»: حالة السير و3 رحلات قادمة.', 'اختر خطك (N1 إلى N4) ومحطتك.', 'تمر الحافلات كل 10 دقائق من 5:00 إلى 23:00.']),
    expressions: ['prochaine navette', 'horaires du bus', 'a quelle heure passe la navette', 'la navette est en retard', 'bus schedule', 'next shuttle', 'horario del autobus', 'proxima lanzadera', 'مواعيد الحافلة'] },
  { id: 'abonnement-transport', service: 'transports', type: 'contact', concepts: ['abonnement', 'transport'],
    titre: L('Abonnement de navette', 'Shuttle pass', 'Abono de lanzadera', 'اشتراك الحافلة'),
    documents: L(['Pièce d’identité', 'Photo'], ['ID', 'Photo'], ['Documento de identidad', 'Foto'], ['وثيقة الهوية', 'صورة']),
    expressions: ['carte de bus', 'abonnement navette', 'pass mensuel', 'recharger ma carte', 'bus pass', 'monthly pass', 'abono de transporte', 'اشتراك الحافلة'] },
  { id: 'tarif-reduit', service: 'transports', type: 'contact', concepts: ['reduction', 'transport'],
    titre: L('Tarif réduit ou gratuité des navettes', 'Reduced or free shuttle fare', 'Tarifa reducida o gratuita', 'تعرفة مخفضة أو مجانية'),
    documents: L(['Justificatif de situation (étudiant, senior, faibles revenus)'], ['Proof of eligibility (student, senior, low income)'], ['Justificante de situación (estudiante, mayor, ingresos bajos)'], ['إثبات الوضعية (طالب، مسن، دخل ضعيف)']),
    expressions: ['navette moins chere', 'reduction etudiant', 'transport gratuit', 'tarif senior', 'cheaper bus', 'student discount', 'descuento estudiante', 'تخفيض للطلاب'] },
  { id: 'objet-perdu', service: 'transports', type: 'contact', concepts: ['perdu'],
    titre: L('Objet perdu dans une navette', 'Item lost on a shuttle', 'Objeto perdido en una lanzadera', 'شيء مفقود في حافلة'),
    documents: L(['Description de l’objet', 'Ligne et heure du trajet'], ['Description of the item', 'Line and time of the trip'], ['Descripción del objeto', 'Línea y hora del trayecto'], ['وصف الشيء', 'الخط ووقت الرحلة']),
    expressions: ['j ai oublie mon sac dans la navette', 'objet perdu', 'perdu mon telephone dans le bus', 'lost my bag on the bus', 'left my phone on the shuttle', 'perdi mi bolso en el autobus', 'نسيت حقيبتي في الحافلة'] },
  { id: 'coupure-eau', service: 'eau-energie', type: 'signalement', categorie: 'eau', concepts: ['eau', 'coupure'],
    titre: L('Plus d’eau au robinet', 'No water from the tap', 'No sale agua del grifo', 'لا يوجد ماء في الحنفية'),
    expressions: ['plus d eau au robinet', 'pas d eau', 'il n y a plus d eau', 'rien ne coule', 'l eau est coupee', 'coupure d eau', 'no water', 'water is off', 'no water from the tap', 'no hay agua', 'sin agua', 'corte de agua', 'لا يوجد ماء', 'انقطاع الماء'] },
  { id: 'fuite-eau', service: 'eau-energie', type: 'signalement', categorie: 'eau', concepts: ['eau', 'fuite'],
    titre: L('Signaler une fuite d’eau', 'Report a water leak', 'Avisar de una fuga de agua', 'الإبلاغ عن تسرب ماء'),
    expressions: ['fuite d eau', 'tuyau perce', 'ca fuit', 'de l eau partout', 'inondation dans la rue', 'water leak', 'burst pipe', 'fuga de agua', 'tuberia rota', 'تسرب الماء'] },
  { id: 'facture-energie', service: 'eau-energie', type: 'contact', concepts: ['facture'],
    titre: L('Question ou contestation de facture', 'Question about or dispute of a bill', 'Pregunta o reclamación de factura', 'سؤال أو اعتراض على فاتورة'),
    documents: L(['La facture concernée', 'Un relevé de compteur'], ['The bill', 'A meter reading'], ['La factura', 'Una lectura del contador'], ['الفاتورة المعنية', 'قراءة العداد']),
    expressions: ['facture trop chere', 'contester ma facture', 'payer ma facture', 'erreur sur ma facture', 'my bill is too high', 'pay my bill', 'factura muy alta', 'pagar la factura', 'فاتورة مرتفعة'] },
  { id: 'coupure-electricite', service: 'eau-energie', type: 'contact', concepts: ['electricite', 'coupure'],
    titre: L('Plus de courant chez moi', 'Power cut at home', 'Sin electricidad en casa', 'انقطاع الكهرباء في منزلي'),
    expressions: ['plus de courant', 'panne d electricite', 'plus d electricite', 'coupure de courant', 'power cut', 'no electricity', 'sin luz', 'corte de luz', 'انقطاع الكهرباء'] },
  { id: 'raccordement', service: 'eau-energie', type: 'contact', concepts: ['electricite', 'eau', 'logement'],
    titre: L('Raccorder un module à l’eau et à l’énergie', 'Connect a module to water and power', 'Conectar un módulo al agua y la energía', 'توصيل وحدة بالماء والطاقة'),
    documents: L(['Attribution du module', 'Pièce d’identité'], ['Module allocation', 'ID'], ['Asignación del módulo', 'Documento de identidad'], ['قرار تخصيص الوحدة', 'وثيقة الهوية']),
    expressions: ['raccorder mon module', 'brancher l eau', 'ouvrir un compteur', 'mettre l electricite', 'get connected to water', 'contratar la luz', 'توصيل الكهرباء'] },
  { id: 'lampadaire', service: 'voirie', type: 'signalement', categorie: 'eclairage', concepts: ['eclairage', 'panne'],
    titre: L('Signaler un lampadaire en panne', 'Report a broken streetlight', 'Avisar de una farola averiada', 'الإبلاغ عن عمود إنارة معطل'),
    expressions: ['lampadaire casse', 'lampadaire eteint', 'lampadaire en panne', 'plus de lumiere dans la rue', 'la rue est dans le noir', 'eclairage en panne', 'streetlight broken', 'street light out', 'farola rota', 'farola apagada', 'عمود الانارة معطل'] },
  { id: 'trou-chaussee', service: 'voirie', type: 'signalement', categorie: 'chaussee', concepts: ['route'],
    titre: L('Signaler un trou ou un trottoir abîmé', 'Report a pothole or damaged pavement', 'Avisar de un bache o una acera dañada', 'الإبلاغ عن حفرة أو رصيف متضرر'),
    expressions: ['trou dans la route', 'nid de poule', 'trottoir abime', 'route defoncee', 'pothole', 'broken pavement', 'bache en la calle', 'acera rota', 'حفرة في الطريق'] },
  { id: 'danger-voie', service: 'voirie', type: 'signalement', categorie: 'autre', concepts: ['danger'], danger: true,
    titre: L('Danger immédiat dans la rue', 'Immediate danger in the street', 'Peligro inmediato en la calle', 'خطر فوري في الشارع'),
    etapes: L(['S’il y a un risque pour quelqu’un : appelez le 112 d’abord.', 'Éloignez-vous et empêchez les autres d’approcher.', 'Puis signalez le lieu exact : il est traité en priorité.'], ['If anyone is at risk: call 112 first.', 'Move away and keep others away.', 'Then report the exact location: it is handled first.'], ['Si alguien corre peligro: llame primero al 112.', 'Aléjese y evite que otros se acerquen.', 'Después indique el lugar exacto: se trata con prioridad.'], ['إذا كان هناك خطر على أحد: اتصل بالرقم 112 أولاً.', 'ابتعد وامنع الآخرين من الاقتراب.', 'ثم أبلغ عن المكان بدقة: يُعالج بالأولوية.']),
    expressions: ['cable electrique tombe', 'fil electrique par terre', 'odeur de gaz', 'arbre tombe sur la route', 'fallen cable', 'gas smell', 'olor a gas', 'cable caido', 'رائحة غاز'] },
  { id: 'poubelle-pleine', service: 'dechets', type: 'signalement', categorie: 'dechets', concepts: ['dechet', 'deborde'],
    titre: L('Poubelle ou conteneur qui déborde', 'Overflowing bin or container', 'Contenedor que desborda', 'حاوية نفايات ممتلئة'),
    expressions: ['ma poubelle deborde', 'poubelle pleine', 'les poubelles debordent', 'conteneur plein', 'poubelles pas ramassees', 'les ordures ne sont pas ramassees', 'bin is full', 'rubbish not collected', 'overflowing bin', 'basura llena', 'contenedor lleno', 'no recogen la basura', 'القمامة ممتلئة'] },
  { id: 'depot-sauvage', service: 'dechets', type: 'signalement', categorie: 'dechets', concepts: ['dechet'],
    titre: L('Dépôt sauvage de déchets', 'Illegal dumping', 'Vertido ilegal', 'رمي عشوائي للنفايات'),
    expressions: ['depot sauvage', 'dechets jetes par terre', 'quelqu un a jete ses dechets', 'illegal dumping', 'fly tipping', 'vertido ilegal', 'basura tirada', 'رمي النفايات'] },
  { id: 'encombrants', service: 'dechets', type: 'info', lien: 'annonces.html#ann-3', concepts: ['encombrant', 'dechet'],
    titre: L('Se débarrasser d’un encombrant', 'Get rid of bulky waste', 'Deshacerse de un objeto voluminoso', 'التخلص من الأغراض الكبيرة'),
    etapes: L(['Collecte des encombrants le samedi : déposez l’objet devant votre module avant 8h.', 'Ou apportez-le au centre de tri (quartier Ouest), tous les jours de 6h à 20h.', 'Plus de 3 objets : écrivez au service Déchets & recyclage.'], ['Bulky waste collection on Saturday: leave the item outside your module before 8am.', 'Or bring it to the recycling centre (West), every day 6am–8pm.', 'More than 3 items: write to Waste & recycling.'], ['Recogida el sábado: deje el objeto frente a su módulo antes de las 8 h.', 'O llévelo al centro de reciclaje (Oeste), todos los días de 6 h a 20 h.', 'Más de 3 objetos: escriba a Residuos y reciclaje.'], ['جمع الأغراض الكبيرة يوم السبت: ضعها أمام وحدتك قبل 8:00.', 'أو احملها إلى مركز الفرز (الغرب) يومياً من 6:00 إلى 20:00.', 'أكثر من 3 أغراض: راسل خدمة النفايات.']),
    expressions: ['jeter un matelas', 'se debarrasser d un frigo', 'vieux meuble', 'jeter un canape', 'bulky waste', 'get rid of a sofa', 'tirar un colchon', 'التخلص من الاثاث'] },
  { id: 'bruit', service: 'dechets', type: 'signalement', categorie: 'bruit', concepts: ['bruit'],
    titre: L('Bruit ou nuisance du voisinage', 'Noise or neighbourhood nuisance', 'Ruido o molestias vecinales', 'ضجيج أو إزعاج من الجوار'),
    expressions: ['voisin bruyant', 'musique trop forte', 'tapage nocturne', 'trop de bruit la nuit', 'noisy neighbours', 'loud music', 'vecinos ruidosos', 'mucho ruido', 'ازعاج الجيران'] },
  { id: 'inscription-scolaire', service: 'education', type: 'demarche', nature: 'ecole', concepts: ['ecole', 'enfant'], clair: 'demarche:ecole',
    titre: L('Inscrire un enfant à l’école', 'Enrol a child at school', 'Inscribir a un niño en la escuela', 'تسجيل طفل في المدرسة'),
    documents: L(['Livret de famille', 'Justificatif de domicile', 'Carnet de santé (vaccins)'], ['Family record book', 'Proof of address', 'Health record (vaccines)'], ['Libro de familia', 'Justificante de domicilio', 'Cartilla de salud (vacunas)'], ['دفتر العائلة', 'إثبات السكن', 'دفتر الصحة (التطعيمات)']),
    expressions: ['inscrire mon fils a l ecole', 'inscrire ma fille a l ecole', 'inscription a l ecole', 'rentree scolaire', 'changer d ecole', 'enrol my child in school', 'school registration', 'matricular a mi hijo', 'inscripcion escolar', 'تسجيل ابني في المدرسة'] },
  { id: 'creche', service: 'education', type: 'demarche', nature: 'ecole', concepts: ['creche', 'enfant'],
    titre: L('Trouver une place en crèche', 'Find a nursery place', 'Encontrar plaza en una guardería', 'إيجاد مكان في الحضانة'),
    documents: L(['Livret de famille', 'Justificatif de domicile', 'Attestation de ressources'], ['Family record book', 'Proof of address', 'Income certificate'], ['Libro de familia', 'Justificante de domicilio', 'Certificado de ingresos'], ['دفتر العائلة', 'إثبات السكن', 'شهادة الدخل']),
    expressions: ['faire garder mon bebe', 'place en creche', 'garde d enfant', 'nursery place', 'childcare', 'plaza de guarderia', 'حضانة للطفل'] },
  { id: 'cantine', service: 'education', type: 'demarche', nature: 'ecole', concepts: ['cantine', 'ecole'],
    titre: L('Inscription à la cantine', 'School canteen registration', 'Inscripción en el comedor', 'التسجيل في المطعم المدرسي'),
    documents: L(['Attestation de ressources'], ['Income certificate'], ['Certificado de ingresos'], ['شهادة الدخل']),
    expressions: ['inscrire a la cantine', 'prix de la cantine', 'repas a l ecole', 'school lunch', 'comedor escolar', 'مطعم المدرسة'] },
  { id: 'recherche-emploi', service: 'emploi', type: 'rdv', concepts: ['emploi'],
    titre: L('Trouver un travail', 'Find a job', 'Encontrar trabajo', 'إيجاد عمل'),
    documents: L(['CV (même simple)', 'Pièce d’identité'], ['CV (even a simple one)', 'ID'], ['Currículum (aunque sea sencillo)', 'Documento de identidad'], ['سيرة ذاتية (ولو بسيطة)', 'وثيقة الهوية']),
    expressions: ['je cherche du travail', 'trouver un boulot', 'je suis au chomage', 'chercher un emploi', 'faire mon cv', 'looking for a job', 'find work', 'busco trabajo', 'estoy en paro', 'ابحث عن عمل'] },
  { id: 'formation', service: 'emploi', type: 'demarche', nature: 'emploi', concepts: ['formation'],
    titre: L('Suivre une formation', 'Take a training course', 'Hacer una formación', 'متابعة تكوين'),
    documents: L(['Projet professionnel', 'Dernier diplôme'], ['Career plan', 'Latest diploma'], ['Proyecto profesional', 'Último diploma'], ['المشروع المهني', 'آخر شهادة']),
    expressions: ['suivre une formation', 'apprendre un metier', 'reprendre mes etudes', 'training course', 'learn a trade', 'curso de formacion', 'دورة تكوينية'] },
  { id: 'aide-urgence', service: 'social', type: 'demarche', nature: 'aide', concepts: ['aide', 'argent', 'alimentation'], clair: 'demarche:aide',
    titre: L('Aide d’urgence (argent, nourriture)', 'Emergency aid (money, food)', 'Ayuda de urgencia (dinero, comida)', 'مساعدة عاجلة (مال، طعام)'),
    documents: L(['Justificatifs de ressources', 'Pièce d’identité'], ['Proof of resources', 'ID'], ['Justificantes de ingresos', 'Documento de identidad'], ['إثبات الموارد', 'وثيقة الهوية']),
    expressions: ['je n ai plus d argent', 'fin de mois difficile', 'je n ai rien a manger', 'colis alimentaire', 'je n arrive pas a payer', 'no money', 'can t afford food', 'no tengo dinero', 'no tengo para comer', 'ليس لدي مال', 'لا املك طعاما'] },
  { id: 'accompagnement-social', service: 'social', type: 'rdv', concepts: ['social', 'aide'],
    titre: L('Être accompagné par un travailleur social', 'Get support from a social worker', 'Recibir apoyo de un trabajador social', 'مرافقة من عامل اجتماعي'),
    documents: L(['Pièce d’identité', 'Les papiers qui posent problème'], ['ID', 'The papers causing trouble'], ['Documento de identidad', 'Los papeles que le causan problemas'], ['وثيقة الهوية', 'الأوراق التي تسبب مشكلة']),
    expressions: ['parler a une assistante sociale', 'rendez vous assistante sociale', 'je suis perdu dans mes papiers', 'aide pour remplir un dossier', 'social worker', 'help filling a form', 'trabajadora social', 'مساعدة اجتماعية'] },
  { id: 'mediatheque', service: 'culture', type: 'info', lien: 'services.html#culture', concepts: ['culture'],
    titre: L('Médiathèque et sorties culturelles', 'Library and cultural outings', 'Mediateca y cultura', 'المكتبة والأنشطة الثقافية'),
    etapes: L(['Dôme culturel, quartier Est : du mardi au dimanche, 10h–20h.', 'Prêt gratuit avec votre compte habitant.', 'Vérifiez d’abord l’état du service sur sa fiche.'], ['Cultural dome, East district: Tuesday to Sunday, 10am–8pm.', 'Free lending with your resident account.', 'Check the service status on its page first.'], ['Cúpula cultural, barrio Este: de martes a domingo, 10–20 h.', 'Préstamo gratuito con su cuenta.', 'Compruebe antes el estado del servicio.'], ['القبة الثقافية، الحي الشرقي: من الثلاثاء إلى الأحد، 10:00–20:00.', 'إعارة مجانية بحساب الساكن.', 'تحقق أولاً من حالة الخدمة.']),
    expressions: ['emprunter un livre', 'bibliotheque', 'horaires de la mediatheque', 'borrow a book', 'library opening', 'biblioteca', 'استعارة كتاب'] },
  { id: 'sport', service: 'culture', type: 'info', lien: 'services.html#culture', concepts: ['sport'],
    titre: L('Salles de sport et piscine', 'Sports halls and pool', 'Gimnasios y piscina', 'القاعات الرياضية والمسبح'),
    etapes: L(['Salles de sport du dôme culturel : du mardi au dimanche, 10h–20h.', 'Accès avec votre compte habitant.', 'Associations sportives : renseignez-vous à l’accueil du dôme.'], ['Cultural dome sports halls: Tuesday to Sunday, 10am–8pm.', 'Access with your resident account.', 'Sports clubs: ask at the dome reception.'], ['Gimnasios de la cúpula cultural: martes a domingo, 10–20 h.', 'Acceso con su cuenta.', 'Clubes: pregunte en la recepción.'], ['قاعات القبة الثقافية: من الثلاثاء إلى الأحد، 10:00–20:00.', 'الدخول بحساب الساكن.', 'الأندية الرياضية: استفسر في الاستقبال.']),
    expressions: ['salle de sport', 'faire du sport', 'aller a la piscine', 'club de foot', 'gym', 'swimming pool', 'gimnasio', 'piscina', 'قاعة رياضة'] },
  { id: 'permis-travaux', service: 'urbanisme', type: 'demarche', nature: 'travaux', concepts: ['urbanisme'], clair: 'demarche:travaux',
    titre: L('Autorisation de travaux ou d’extension', 'Building or extension permit', 'Licencia de obras o ampliación', 'رخصة أشغال أو توسيع'),
    documents: L(['Plan du projet', 'Photos du module', 'Attribution du module'], ['Project plan', 'Photos of the module', 'Module allocation'], ['Plano del proyecto', 'Fotos del módulo', 'Asignación del módulo'], ['مخطط المشروع', 'صور الوحدة', 'قرار التخصيص']),
    expressions: ['agrandir mon module', 'construire une veranda', 'permis de construire', 'autorisation de travaux', 'faire des travaux', 'building permit', 'extend my home', 'licencia de obras', 'ampliar mi casa', 'رخصة بناء'] },
  { id: 'suivre-demande', service: '', type: 'info', lien: 'espace.html', concepts: ['suivi'],
    titre: L('Suivre une demande déjà envoyée', 'Track a request already sent', 'Seguir una solicitud enviada', 'متابعة طلب مُرسل'),
    etapes: L(['Ouvrez « Suivre mes demandes » (ou votre accusé de réception).', 'Chaque étape est datée : reçue, en cours, traitée.', 'Pas de nouvelles après le délai ? Répondez dans le fil de votre demande.'], ['Open “Track my requests” (or your receipt).', 'Each step is dated: received, in progress, resolved.', 'No news after the deadline? Reply in your request thread.'], ['Abra «Seguir mis solicitudes» (o su acuse de recibo).', 'Cada etapa tiene fecha: recibida, en curso, resuelta.', '¿Sin noticias tras el plazo? Responda en el hilo de su solicitud.'], ['افتح «متابعة طلباتي» (أو إشعار الاستلام).', 'كل مرحلة مؤرخة: مستلمة، قيد المعالجة، تمت المعالجة.', 'لا أخبار بعد المهلة؟ ردّ في سلسلة طلبك.']),
    expressions: ['ou en est ma demande', 'suivre mon dossier', 'suivre ma demande', 'toujours pas de reponse', 'mon numero de demande', 'track my request', 'status of my request', 'estado de mi solicitud', 'متابعة طلبي'] },
  { id: 'prendre-rdv', service: '', type: 'rdv', concepts: ['rdv'],
    titre: L('Prendre rendez-vous avec un agent', 'Book an appointment with a staff member', 'Pedir cita con un agente', 'حجز موعد مع عون'),
    expressions: ['prendre rendez vous', 'rdv a la mairie', 'rencontrer un agent', 'book an appointment', 'make an appointment', 'pedir cita', 'حجز موعد'] },
  { id: 'compte', service: '', type: 'info', lien: 'connexion.html', concepts: ['compte'],
    titre: L('Se connecter, mot de passe oublié', 'Sign in, forgotten password', 'Iniciar sesión, contraseña olvidada', 'تسجيل الدخول، كلمة السر المنسية'),
    etapes: L(['Ouvrez « Connexion » en haut de la page.', 'Sans e-mail : utilisez votre identifiant TN et votre code secret.', 'Mot de passe oublié : l’accueil de la mairie vous redonne l’accès avec une pièce d’identité.'], ['Open “Sign in” at the top of the page.', 'No e-mail: use your TN ID and secret code.', 'Forgotten password: city hall reception restores access with an ID.'], ['Abra «Iniciar sesión» arriba.', 'Sin correo: use su identificador TN y su código.', 'Contraseña olvidada: la recepción del ayuntamiento le devuelve el acceso con un documento de identidad.'], ['افتح «تسجيل الدخول» أعلى الصفحة.', 'بدون بريد: استعمل معرّف TN ورمزك السري.', 'كلمة السر المنسية: يعيد لك استقبال البلدية الدخول بوثيقة هوية.']),
    expressions: ['mot de passe oublie', 'je n arrive pas a me connecter', 'creer un compte', 'pas d adresse mail', 'forgot my password', 'cannot log in', 'olvide mi contrasena', 'crear una cuenta', 'نسيت كلمة السر'] },
  { id: 'donnees-perso', service: '', type: 'info', lien: 'donnees.html', concepts: ['donnees'], clair: 'page:donnees',
    titre: L('Mes données personnelles', 'My personal data', 'Mis datos personales', 'بياناتي الشخصية'),
    etapes: L(['« Vos données » explique ce que la ville garde et pourquoi.', '« Mes informations » montre tout ce qui vous concerne, téléchargeable.', 'Une question ou une inquiétude : écrivez depuis cette page, réponse d’un agent.'], ['“Your data” explains what the city keeps and why.', '“My information” shows everything about you, downloadable.', 'A question or concern: write from that page, a staff member answers.'], ['«Sus datos» explica qué guarda la ciudad y por qué.', '«Mi información» muestra todo lo suyo, descargable.', 'Una pregunta: escriba desde esa página, responde un agente.'], ['«بياناتك» تشرح ما تحتفظ به المدينة ولماذا.', '«معلوماتي» تعرض كل ما يخصك، قابلة للتنزيل.', 'سؤال أو قلق: اكتب من تلك الصفحة ويجيبك عون.']),
    expressions: ['mes donnees personnelles', 'supprimer mes donnees', 'que faites vous de mes donnees', 'my personal data', 'delete my data', 'mis datos personales', 'بياناتي الشخصية'] },
  { id: 'nouvel-arrivant', service: '', type: 'info', lien: 'bienvenue.html#guide', concepts: ['arrivee'],
    titre: L('Je viens d’arriver à Terra Nova', 'I have just arrived in Terra Nova', 'Acabo de llegar a Terra Nova', 'وصلت للتو إلى تيرا نوفا'),
    etapes: L(['Le guide « Je viens d’arriver » : 3 questions, une liste de services pour vous.', 'Créez votre compte (même sans e-mail).', 'Indiquez votre quartier pour recevoir les bonnes alertes.'], ['The “I just arrived” guide: 3 questions, a list of services for you.', 'Create your account (even without e-mail).', 'Add your district to receive the right alerts.'], ['La guía «Acabo de llegar»: 3 preguntas, una lista de servicios para usted.', 'Cree su cuenta (incluso sin correo).', 'Indique su barrio para recibir las alertas adecuadas.'], ['دليل «وصلت للتو»: 3 أسئلة وقائمة خدمات لك.', 'أنشئ حسابك (حتى بدون بريد).', 'حدد حيّك لتصلك التنبيهات المناسبة.']),
    expressions: ['je viens d arriver', 'nouveau dans la ville', 'je m installe', 'premiere fois ici', 'just arrived', 'new in town', 'acabo de llegar', 'soy nuevo', 'وصلت حديثا'] },
  { id: 'horaires-mairie', service: 'etat-civil', type: 'info', lien: 'carte.html?lieu=hotel-ville', concepts: ['mairie', 'horaire'],
    titre: L('Horaires et adresse de la mairie', 'City hall opening hours and address', 'Horario y dirección del ayuntamiento', 'مواعيد وعنوان البلدية'),
    etapes: L(['Hôtel de ville : 1 place de la Mairie, niveau 1.', 'Lundi au vendredi 8h–17h, jeudi jusqu’à 19h.', 'En ligne, Terra Nova est ouverte 24 h/24.'], ['City hall: 1 Mairie square, level 1.', 'Monday to Friday 8am–5pm, Thursday until 7pm.', 'Online, Terra Nova is open 24/7.'], ['Ayuntamiento: plaza de la Mairie 1, nivel 1.', 'De lunes a viernes 8–17 h, jueves hasta las 19 h.', 'En línea, abierto 24 h.'], ['دار البلدية: 1 ساحة البلدية، الطابق 1.', 'من الاثنين إلى الجمعة 8:00–17:00، والخميس حتى 19:00.', 'عبر الإنترنت: مفتوحة على مدار الساعة.']),
    expressions: ['horaires de la mairie', 'la mairie est ouverte', 'adresse de la mairie', 'city hall opening hours', 'when is the town hall open', 'horario del ayuntamiento', 'مواعيد البلدية'] },
  { id: 'reclamation', service: '', type: 'contact', concepts: ['plainte'],
    titre: L('Faire une réclamation', 'Make a complaint', 'Presentar una queja', 'تقديم شكوى'),
    expressions: ['faire une reclamation', 'porter plainte contre la mairie', 'je suis mecontent', 'make a complaint', 'presentar una queja', 'تقديم شكوى'] },
  { id: 'chaleur', service: 'sante', type: 'info', lien: 'annonces.html#ann-chaleur', concepts: ['chaleur'],
    titre: L('Se protéger de la chaleur', 'Stay safe in the heat', 'Protegerse del calor', 'الحماية من الحر'),
    etapes: L(['Buvez de l’eau souvent, restez au frais aux heures chaudes.', 'Espaces rafraîchis : dôme des Pionniers (Sud) et Résidence Aurore (Est).', 'Malaise d’une personne âgée ou d’un enfant : appelez le 15.'], ['Drink water often, stay cool in the hottest hours.', 'Cooling spaces: Pioneers dome (South) and Aurore residence (East).', 'An elderly person or child feels unwell: call 15.'], ['Beba agua a menudo y quédese a la sombra.', 'Espacios frescos: cúpula de los Pioneros (Sur) y residencia Aurora (Este).', 'Si una persona mayor o un niño se encuentra mal: llame al 15.'], ['اشرب الماء كثيراً وابقَ في مكان بارد.', 'أماكن مبرّدة: قبة الرواد (الجنوب) وإقامة أورور (الشرق).', 'إذا شعر مسن أو طفل بتوعك: اتصل بالرقم 15.']),
    expressions: ['il fait trop chaud', 'lieu frais', 'canicule', 'heatwave', 'too hot', 'ola de calor', 'الحر شديد'] },
  { id: 'urgence', service: 'sante', type: 'urgence', concepts: ['urgence'],
    titre: L('Urgence : appeler les secours', 'Emergency: call for help', 'Urgencia: llamar a emergencias', 'طوارئ: اتصل بالإسعاف'),
    expressions: ['appeler une ambulance', 'appeler les pompiers', 'c est une urgence', 'call an ambulance', 'it is an emergency', 'llamar a una ambulancia', 'اتصل بالاسعاف'] }
];

/* ---------- Réponses courtes (questions fréquentes) ---------- */
const REPONSES = [
  { id: 'delais', concepts: ['suivi'], lien: 'aide.html#faq',
    q: L('Combien de temps pour avoir une réponse ?', 'How long until I get an answer?', '¿Cuánto tarda la respuesta?', 'كم من الوقت للحصول على رد؟'),
    r: L('Message à un service : 3 jours ouvrés. Signalement : 48 heures (4 heures si c’est dangereux). Démarche : 5 jours ouvrés.', 'Message to a service: 3 working days. Report: 48 hours (4 hours if dangerous). Procedure: 5 working days.', 'Mensaje: 3 días laborables. Aviso: 48 horas (4 si es peligroso). Trámite: 5 días laborables.', 'رسالة: 3 أيام عمل. بلاغ: 48 ساعة (4 ساعات إذا كان خطيراً). إجراء: 5 أيام عمل.'),
    mots: 'delai combien de temps reponse attendre how long wait cuanto tarda plazo مهلة' },
  { id: 'sans-compte', concepts: ['compte'], lien: 'demande.html?type=contact',
    q: L('Puis-je faire une demande sans compte ?', 'Can I make a request without an account?', '¿Puedo hacer una solicitud sin cuenta?', 'هل يمكنني تقديم طلب بدون حساب؟'),
    r: L('Oui, pour un message ou un signalement : laissez votre nom et votre e-mail. Pour suivre vos démarches, un compte est plus simple.', 'Yes, for a message or a report: leave your name and e-mail. To follow procedures, an account is easier.', 'Sí, para un mensaje o un aviso: deje su nombre y correo. Para seguir trámites, una cuenta es más cómoda.', 'نعم، للرسالة أو البلاغ: اترك اسمك وبريدك. لمتابعة الإجراءات، الحساب أسهل.'),
    mots: 'sans compte visiteur anonyme without account sin cuenta بدون حساب' },
  { id: 'sans-email', concepts: ['compte'], lien: 'bienvenue.html#sans-email',
    q: L('Je n’ai pas d’adresse e-mail', 'I don’t have an e-mail address', 'No tengo correo electrónico', 'ليس لدي بريد إلكتروني'),
    r: L('Créez un compte avec un identifiant TN et un code secret de 6 chiffres, en ligne ou au guichet de la mairie.', 'Create an account with a TN ID and a 6-digit secret code, online or at the city hall desk.', 'Cree una cuenta con un identificador TN y un código de 6 cifras, en línea o en la ventanilla.', 'أنشئ حساباً بمعرّف TN ورمز سري من 6 أرقام، عبر الإنترنت أو في شباك البلدية.'),
    mots: 'pas de mail email courriel adresse electronique no email sin correo بريد' },
  { id: 'urgences', concepts: ['urgence'], lien: 'carte.html?filtre=urgence',
    q: L('Que faire en cas d’urgence ?', 'What to do in an emergency?', '¿Qué hacer en caso de urgencia?', 'ماذا أفعل في حالة طارئة؟'),
    r: L('Appelez le 15 (urgence médicale) ou le 112 (toutes urgences). Terra Nova ne remplace pas les secours.', 'Call 15 (medical emergency) or 112 (all emergencies). Terra Nova does not replace emergency services.', 'Llame al 15 (urgencia médica) o al 112. Terra Nova no sustituye a emergencias.', 'اتصل بالرقم 15 (طوارئ طبية) أو 112 (كل الطوارئ). تيرا نوفا لا تحل محل الإسعاف.'),
    mots: 'urgence secours samu pompiers emergency urgencia طوارئ' },
  { id: 'langues', concepts: [], lien: 'aide.html',
    q: L('Le site existe-t-il dans ma langue ?', 'Is the site available in my language?', '¿Está la web en mi idioma?', 'هل الموقع متاح بلغتي؟'),
    r: L('Oui : français, anglais, espagnol et arabe, avec le sélecteur de langue en haut de chaque page.', 'Yes: French, English, Spanish and Arabic, with the language selector at the top of each page.', 'Sí: francés, inglés, español y árabe, con el selector de idioma arriba.', 'نعم: الفرنسية والإنجليزية والإسبانية والعربية، عبر محدد اللغة أعلى كل صفحة.'),
    mots: 'langue traduction anglais espagnol arabe language translate english spanish arabic idioma ingles لغة عربية' },
  { id: 'rdv-annuler', concepts: ['rdv'], lien: 'rendez-vous.html',
    q: L('Comment annuler ou déplacer un rendez-vous ?', 'How do I cancel or move an appointment?', '¿Cómo anulo o cambio una cita?', 'كيف ألغي أو أغير موعداً؟'),
    r: L('Dans « Rendez-vous », section « Mes rendez-vous » : bouton Annuler, puis choisissez un nouveau créneau.', 'In “Appointments”, “My appointments”: Cancel button, then choose a new slot.', 'En «Citas», «Mis citas»: botón Anular y elija otro horario.', 'في «المواعيد» ثم «مواعيدي»: زر الإلغاء ثم اختر موعداً جديداً.'),
    mots: 'annuler deplacer changer reporter cancel move reschedule anular cambiar الغاء' },
  { id: 'accessibilite', concepts: [], lien: 'aide.html',
    q: L('Le texte est trop petit ou difficile à lire', 'The text is too small or hard to read', 'El texto es demasiado pequeño o difícil', 'النص صغير جداً أو صعب القراءة'),
    r: L('Le bouton ♿ en haut agrandit le texte, renforce le contraste et espace les lignes. « Expliquer plus simplement » reformule les passages difficiles.', 'The ♿ button at the top enlarges text, boosts contrast and spaces lines. “Explain more simply” rephrases hard passages.', 'El botón ♿ agranda el texto, refuerza el contraste y espacia las líneas. «Explicar más sencillo» reformula los pasajes difíciles.', 'زر ♿ في الأعلى يكبّر النص ويقوّي التباين. «اشرح ببساطة» يعيد صياغة المقاطع الصعبة.'),
    mots: 'petit lire lecture difficile comprendre agrandir malvoyant small read hard understand pequeno leer dificil صغير قراءة' },
  { id: 'paiement', concepts: ['facture'], lien: 'services.html#eau-energie',
    q: L('Comment payer une facture de la ville ?', 'How do I pay a city bill?', '¿Cómo pago una factura?', 'كيف أدفع فاتورة المدينة؟'),
    r: L('Au guichet de la centrale du dôme Nord (lundi au samedi, 8h–18h). Une question sur le montant : écrivez au service Eau & énergie.', 'At the North dome plant desk (Monday to Saturday, 8am–6pm). A question about the amount: write to Water & energy.', 'En la ventanilla de la central de la cúpula Norte (lun–sáb, 8–18 h). Dudas sobre el importe: escriba a Agua y energía.', 'في شباك محطة القبة الشمالية (الاثنين–السبت 8:00–18:00). سؤال عن المبلغ: راسل خدمة الماء والطاقة.'),
    mots: 'payer paiement regler pay payment pagar دفع' }
];

module.exports = { CONCEPTS, SERVICES, ETAPES, BESOINS, REPONSES, L };
